# Generated by Django 3.2.5 on 2023-06-02 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfeel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('acronyms', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Therapy',
                'verbose_name_plural': 'Therapies',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('therapies', models.ManyToManyField(related_name='doctors', to='appfeel.Therapies')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
