# Generated by Django 3.2.5 on 2023-06-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfeel', '0002_doctorprofile_therapies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
