# Generated by Django 4.2.2 on 2023-06-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appfeel", "0003_auto_20230602_0241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="therapies",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="doctors", to="appfeel.therapies"
            ),
        ),
    ]
